### PR TITLE
Now overwrites file and directory permissions

### LINKED ISSUE #51: When using the overwrite to disk writer, permissions are not honoured
**Describe the bug**
When using files.WriteToDisk with overwrite enabled and a file already existing, the files do not get an updated permission set.

**To Reproduce**
This is not a CLI call, simply an export issue.

**Expected behavior**
File permission should be honoured.

**Screenshots**
None.

**Additional context**
None.

### PR DESCRIPTION
**Pull request by LynxPlay101**
If overwrite is set to true when calling WriteToDisk, pina-golada now
overwrites the file permission set if it does not match the one of the
virtual file system.

This push request fixes #51

### CODE REVIEW

File: pkg/files/files_test.go [hunk 1]
```diff
@@ -169,4 +170,42 @@ var _ = Describe("should handle files properly", func() {
...
+		Expect(LoadFromDisk(root, pathToTestDir)).To(BeNil())
+		file := root.File(paths.Of("permission.txt"))
+		Expect(file).To(Not(BeNil()))
+
+		file.WithPermission(os.FileMode(0701))
+		Expect(WriteToDisk(root, pathToTestDir, true)).To(BeNil())
+		Expect(GetFilePermission(pathToTestFile)).To(BeEquivalentTo(os.FileMode(0701)))
+	})
+
+	_ = It("should overwrite permission sets on folders", func() {
```
Comment (HeavyWombat) [inline pkg/files/files_test.go]: Just one tiny suggestion here: `folder` is the term that Microsoft popularised with Windows. If possible, I always try to use the older term `directory`.

Comment (LynxPlay101) [reply pkg/files/files_test.go]: I'll change it 👍
